server:
  port: 9001

spring:
  application:
    name: oauth-server

eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/
  instance:
    prefer-ip-address: true

